name: Test Project workflow
on: push
jobs:
  test_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo # Getting the code from repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test